language: ruby
rvm:
- 2.1.1
env:
- DB=postgresql
script:
- RAILS_ENV=test bundle exec rake db:migrate --trace
- bundle exec rake
before_script:
- cp config/database.yml.travis config/database.yml
- psql -c 'create database travis_ci_test' -U postgres
deploy:
  provider: heroku
  app:
    master: sigma-project
    dev: sigma-project-dev
  run:
  - rake db:migrate
  - restart
  - rake cleanup
  api_key:
    secure: EB3UN8SUXVn3uUagbRqtaNcFpAUQNornFOM56+5cfLIl4sYYodisUAdFBkXBzM5Yn4pgRuaGN62fv+amTot9JmjC+7WYCXd++2J2Dc3sJBGfBtO7zqU5iBJNelskL6fZWXLhHXjvWu2jBb8gPG6v+THtXyHPCAH7/4YcmIatNgA=
