language: ruby
rvm:
  - 2.1.1
env:
  - DB=postgresql
script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake
before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database travis_ci_test' -U postgres
deploy:
  provider: heroku
  api_key:
    secure: "IDqpUlK6NK22EuODyZlO/nMCkhNGxEnWxOi4SMtU+qxKsBKJMRpw4rhEjid59gChOEVEAHTGZQo/ZQCidAT5/hGPE8DIv1TOFT52p9w3VWU52myhWlS6AF6WCGsIbKgJs2UqC2A/Ccl6iAAOD569XJJdJbD4MgMmp2Ez98QM+yI="
  app: sigma-project
  repo: volodya8bit/sigma_project
  run:
    - "rake db:migrate"
    - restart
    - "rake cleanup"
